services:
  pallet_detection:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: pallet_detection_container
    volumes:
      - ../:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility


